version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: synapsenet-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/models:/app/models:ro

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: synapsenet-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend

networks:
  default:
    name: synapsenet
